true_env = ["../../data/hyperparam/gridworld/online_learning/esarsa/150/gridsearch_realenv/"]

data_alltransitions_k1 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k1/step150/all-transitions/"]
data_badpolicy_k1 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k1/step150/bad-policy/"]
data_learningpolicy_k1 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k1/step150/learning-policy/"]
data_nearoptimalbetterpolicy_k1 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k1/step150/nearoptimal-better-policy/"]
data_nearoptimalworsepolicy_k1 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k1/step150/nearoptimal-worse-policy/"]
data_optimalpolicy_k1 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k1/step150/optimal-policy/"]
data_optimalpolicyexploringstarts_k1 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k1/step150/optimal-policy-exploringstarts/"]
data_randompolicy_k1 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k1/step150/random-policy/"]

data_alltransitions_k3 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k3/step150/all-transitions/"]
data_badpolicy_k3 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k3/step150/bad-policy/"]
data_learningpolicy_k3 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k3/step150/learning-policy/"]
data_nearoptimalbetterpolicy_k3 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k3/step150/nearoptimal-better-policy/"]
data_nearoptimalworsepolicy_k3 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k3/step150/nearoptimal-worse-policy/"]
data_optimalpolicy_k3 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k3/step150/optimal-policy/"]
data_optimalpolicyexploringstarts_k3 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k3/step150/optimal-policy-exploringstarts/"]
data_randompolicy_k3 = ["../../data/hyperparam/gridworld/offline_learning/knn-ensemble/k3/step150/random-policy/"]