// Code generated by protoc-gen-go. DO NOT EDIT.
// source: environment.proto

package remote

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Attributes struct {
	Attributes           string   `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attributes) Reset()         { *m = Attributes{} }
func (m *Attributes) String() string { return proto.CompactTextString(m) }
func (*Attributes) ProtoMessage()    {}
func (*Attributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{0}
}

func (m *Attributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attributes.Unmarshal(m, b)
}
func (m *Attributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attributes.Marshal(b, m, deterministic)
}
func (m *Attributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attributes.Merge(m, src)
}
func (m *Attributes) XXX_Size() int {
	return xxx_messageInfo_Attributes.Size(m)
}
func (m *Attributes) XXX_DiscardUnknown() {
	xxx_messageInfo_Attributes.DiscardUnknown(m)
}

var xxx_messageInfo_Attributes proto.InternalMessageInfo

func (m *Attributes) GetAttributes() string {
	if m != nil {
		return m.Attributes
	}
	return ""
}

type State struct {
	Values               []float64 `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{1}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type Action struct {
	Action               uint64   `protobuf:"fixed64,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{2}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetAction() uint64 {
	if m != nil {
		return m.Action
	}
	return 0
}

type StepResult struct {
	State                *State   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Reward               float64  `protobuf:"fixed64,2,opt,name=reward,proto3" json:"reward,omitempty"`
	Terminal             bool     `protobuf:"varint,3,opt,name=terminal,proto3" json:"terminal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StepResult) Reset()         { *m = StepResult{} }
func (m *StepResult) String() string { return proto.CompactTextString(m) }
func (*StepResult) ProtoMessage()    {}
func (*StepResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{3}
}

func (m *StepResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StepResult.Unmarshal(m, b)
}
func (m *StepResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StepResult.Marshal(b, m, deterministic)
}
func (m *StepResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StepResult.Merge(m, src)
}
func (m *StepResult) XXX_Size() int {
	return xxx_messageInfo_StepResult.Size(m)
}
func (m *StepResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StepResult.DiscardUnknown(m)
}

var xxx_messageInfo_StepResult proto.InternalMessageInfo

func (m *StepResult) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *StepResult) GetReward() float64 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func (m *StepResult) GetTerminal() bool {
	if m != nil {
		return m.Terminal
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Attributes)(nil), "Attributes")
	proto.RegisterType((*State)(nil), "State")
	proto.RegisterType((*Action)(nil), "Action")
	proto.RegisterType((*StepResult)(nil), "StepResult")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() { proto.RegisterFile("environment.proto", fileDescriptor_64e647b85623514a) }

var fileDescriptor_64e647b85623514a = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x63, 0x4a, 0xdd, 0x72, 0x11, 0x03, 0x37, 0xa0, 0x10, 0xa1, 0x12, 0x19, 0x09, 0x65,
	0x40, 0x1e, 0xca, 0x2f, 0xe8, 0x50, 0x21, 0x56, 0x77, 0x47, 0x72, 0xc1, 0x83, 0xa5, 0xc4, 0x89,
	0x9c, 0x4b, 0x11, 0xfc, 0x0f, 0xfe, 0x2f, 0xb2, 0x13, 0x9a, 0x6c, 0x7e, 0x4f, 0xcf, 0xef, 0xee,
	0x3b, 0xb8, 0x31, 0xee, 0x64, 0x7d, 0xe3, 0x6a, 0xe3, 0x48, 0xb6, 0xbe, 0xa1, 0x46, 0x3c, 0x03,
	0xec, 0x88, 0xbc, 0x3d, 0xf6, 0x64, 0x3a, 0xdc, 0x00, 0xe8, 0xb3, 0xca, 0x58, 0xc1, 0xca, 0x2b,
	0x35, 0x73, 0xc4, 0x03, 0x2c, 0x0f, 0xa4, 0xc9, 0xe0, 0x2d, 0xf0, 0x93, 0xae, 0xfa, 0x18, 0x5a,
	0x94, 0x4c, 0x8d, 0x4a, 0x14, 0xc0, 0x77, 0x1f, 0x64, 0x1b, 0x17, 0x12, 0x3a, 0xbe, 0x62, 0x0d,
	0x57, 0xa3, 0x12, 0xef, 0x00, 0x07, 0x32, 0xad, 0x32, 0x5d, 0x5f, 0x11, 0xde, 0xc3, 0xb2, 0x0b,
	0x85, 0x31, 0x94, 0x6e, 0xb9, 0x8c, 0xf5, 0x6a, 0x30, 0x43, 0x87, 0x37, 0x5f, 0xda, 0x7f, 0x66,
	0x17, 0x05, 0x0b, 0x53, 0x06, 0x85, 0x39, 0xac, 0xc9, 0xf8, 0xda, 0x3a, 0x5d, 0x65, 0x8b, 0x82,
	0x95, 0x6b, 0x75, 0xd6, 0x62, 0x05, 0xcb, 0x7d, 0xdd, 0xd2, 0xf7, 0xf6, 0x97, 0x41, 0xba, 0x9f,
	0x78, 0xf1, 0x11, 0xe0, 0xcd, 0x59, 0xb2, 0xba, 0xb2, 0x3f, 0x06, 0x53, 0x39, 0x61, 0xe7, 0x5c,
	0xc6, 0x2f, 0x22, 0xc1, 0xbb, 0x08, 0xe8, 0x09, 0x47, 0x2b, 0x1f, 0x37, 0x12, 0x09, 0x6e, 0xe0,
	0x32, 0x2c, 0x8e, 0x2b, 0x39, 0x10, 0xe6, 0xa9, 0x9c, 0x40, 0x44, 0x82, 0x4f, 0x70, 0xfd, 0x6a,
	0x68, 0x76, 0xcc, 0xff, 0x8a, 0xf9, 0x28, 0x91, 0x1c, 0x79, 0x3c, 0xfc, 0xcb, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x37, 0x03, 0xb7, 0x11, 0x8d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EnvironmentClient is the client API for Environment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnvironmentClient interface {
	Initialize(ctx context.Context, in *Attributes, opts ...grpc.CallOption) (*Empty, error)
	Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*State, error)
	Step(ctx context.Context, in *Action, opts ...grpc.CallOption) (*StepResult, error)
	GetAttributes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Attributes, error)
}

type environmentClient struct {
	cc *grpc.ClientConn
}

func NewEnvironmentClient(cc *grpc.ClientConn) EnvironmentClient {
	return &environmentClient{cc}
}

func (c *environmentClient) Initialize(ctx context.Context, in *Attributes, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/Environment/Initialize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/Environment/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) Step(ctx context.Context, in *Action, opts ...grpc.CallOption) (*StepResult, error) {
	out := new(StepResult)
	err := c.cc.Invoke(ctx, "/Environment/Step", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentClient) GetAttributes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Attributes, error) {
	out := new(Attributes)
	err := c.cc.Invoke(ctx, "/Environment/GetAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvironmentServer is the server API for Environment service.
type EnvironmentServer interface {
	Initialize(context.Context, *Attributes) (*Empty, error)
	Start(context.Context, *Empty) (*State, error)
	Step(context.Context, *Action) (*StepResult, error)
	GetAttributes(context.Context, *Empty) (*Attributes, error)
}

func RegisterEnvironmentServer(s *grpc.Server, srv EnvironmentServer) {
	s.RegisterService(&_Environment_serviceDesc, srv)
}

func _Environment_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attributes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Environment/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).Initialize(ctx, req.(*Attributes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Environment/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).Start(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Environment/Step",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).Step(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Environment_GetAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServer).GetAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Environment/GetAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServer).GetAttributes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Environment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Environment",
	HandlerType: (*EnvironmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _Environment_Initialize_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Environment_Start_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _Environment_Step_Handler,
		},
		{
			MethodName: "GetAttributes",
			Handler:    _Environment_GetAttributes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "environment.proto",
}
